name: Tests

on:
  push:
    branches:
      - main
    paths:
      - project/**

jobs:
  project-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Set up Jayvee
        run: "npm install -g @jvalue/jayvee-interpreter"

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: 3.12

      - name: Install Dependencies
        run: "pip install -r requirements.txt"
  
      - name: Run tests
        run: "./tests.sh"